# Generated by Django 5.1.3 on 2025-03-18 19:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='theCourse',
            field=models.ForeignKey(default='6d1fb8cf-8201-4292-b53b-c0c4057f35d5', on_delete=django.db.models.deletion.CASCADE, related_name='theCourse', to='backendApp.courses'),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='forDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 3, 18))]),
        ),
    ]
