# Generated by Django 5.1.3 on 2025-03-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_timetable_thecourse_alter_leaverequests_fordate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableclassdistribution',
            name='course',
        ),
    ]
