# Generated by Django 5.1.3 on 2025-03-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_timetableclassdistribution_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='theCourse',
        ),
        migrations.AlterField(
            model_name='timetableclassdistribution',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='backendApp.courses'),
        ),
    ]
