# Generated by Django 5.1.3 on 2025-03-22 19:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_remove_timetable_thecourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequests',
            name='forClass',
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='forDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 3, 22))]),
        ),
    ]
