# Generated by Django 5.1.3 on 2025-03-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_remove_leaverequests_forclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='forCourse',
            field=models.ForeignKey(default='6d1fb8cf-8201-4292-b53b-c0c4057f35d5', on_delete=django.db.models.deletion.CASCADE, related_name='forCourse', to='backendApp.courses'),
        ),
    ]
