# Generated by Django 5.1.3 on 2025-03-24 18:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_leaverequests_forcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='forDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 3, 24))]),
        ),
    ]
