# Generated by Django 5.1.3 on 2025-04-12 11:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0008_alter_leaverequests_fordate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='deanOf',
            field=models.ForeignKey(default='a5b4705d-929b-46c0-b911-fe5e60fcd75c', on_delete=django.db.models.deletion.CASCADE, related_name='deanOf', to='backendApp.departments'),
        ),
        migrations.AddField(
            model_name='admins',
            name='secureKey',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='forDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 12))]),
        ),
    ]
